spring:
  profiles: 
    active: 
      - dev
      
      
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zhm-dev      
    
    
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-zhm-test     